my_string = "My String"

# print("string1", "string2", "string3")

print(my_string)

def test(a, b, c)
    print(a, b, c)
end

print(my_string)

class Test
    b = "5"

    def constructor(a)
        self.a = a
    end

    def test
        b = 10

        self.test2(b)
    end

    def test2(a)
        while true
            print(a)
            break
        end
    end
end

a = Test("Hello")
a.test()
